# Generated by Django 5.1.4 on 2024-12-29 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('release_date', models.DateField()),
                ('genre', models.CharField(choices=[('Pop', 'Pop'), ('Jazz', 'Jazz'), ('Rock', 'Rock'), ('Hip-Hop', 'Hip-Hop'), ('Jazz', 'Jazz'), ('Electronic', 'Electronic'), ('Mixed', 'Mixed'), ('Other', 'Other')], max_length=50)),
                ('no_of_songs', models.PositiveIntegerField(default=10)),
                ('image', models.ImageField(upload_to='albums/')),
            ],
            options={
                'verbose_name_plural': 'Albums',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Pop', 'Pop'), ('Rock', 'Rock'), ('Hip-Hop', 'Hip-Hop'), ('Jazz', 'Jazz'), ('Electronic', 'Electronic'), ('Other', 'Other')], max_length=50)),
                ('birth_date', models.DateField()),
                ('nationality', models.CharField(max_length=50)),
                ('biography', models.TextField()),
                ('image', models.ImageField(upload_to='artists/')),
            ],
            options={
                'verbose_name_plural': 'Artists',
                'ordering': ['birth_date'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('song_cover', models.FileField(upload_to='song_cover/')),
                ('artist', models.CharField(max_length=100)),
                ('popularity', models.PositiveBigIntegerField(default=0)),
                ('no_of_lisners', models.PositiveBigIntegerField(default=0)),
                ('duration', models.DurationField()),
                ('genre', models.CharField(max_length=50)),
                ('track_number', models.PositiveIntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='musicapp.album')),
            ],
            options={
                'verbose_name_plural': 'Songs',
                'ordering': ['title'],
            },
        ),
    ]
