# Generated by Django 5.1.4 on 2024-12-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_cover',
            field=models.ImageField(upload_to='song_cover/'),
        ),
    ]
