# Generated by Django 5.1.4 on 2025-06-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songcomment',
            name='song',
        ),
        migrations.RemoveField(
            model_name='songcomment',
            name='user',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='collaborators',
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(related_name='playlists', to='musicapp.song'),
        ),
        migrations.DeleteModel(
            name='PlaylistSong',
        ),
        migrations.DeleteModel(
            name='SongComment',
        ),
    ]
