# Generated by Django 5.1.4 on 2025-01-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_remove_song_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_cover_url',
            field=models.ImageField(blank=True, null=True, upload_to='song_covers/'),
        ),
    ]
