# Generated by Django 5.1.4 on 2025-01-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_artist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_cover',
            field=models.ImageField(blank=True, null=True, upload_to='song_covers/'),
        ),
    ]
