# Generated by Django 5.1.4 on 2024-12-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_alter_song_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('Pop', 'Pop'), ('Rock', 'Rock'), ('Hip-Hop', 'Hip-Hop'), ('Jazz', 'Jazz'), ('Electronic', 'Electronic'), ('Other', 'Other')], max_length=50),
        ),
    ]
