# Generated by Django 5.1.4 on 2025-06-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_recentlyplayed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='audio_duration',
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
