# Generated by Django 5.1.4 on 2025-01-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_song_song_cover_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_cover_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
