# Generated by Django 5.1.4 on 2024-12-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_alter_song_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='no_of_lisners',
            new_name='no_of_listeners',
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Pop', 'Pop'), ('Jazz', 'Jazz'), ('Rock', 'Rock'), ('Hip-Hop', 'Hip-Hop'), ('Electronic', 'Electronic'), ('Mixed', 'Mixed'), ('Other', 'Other')], max_length=50),
        ),
    ]
