# Generated by Django 5.1.4 on 2025-06-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0005_playlist_cover_image_playlist_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='top_album',
            field=models.BooleanField(default=False),
        ),
    ]
