# Generated by Django 5.1.4 on 2024-12-29 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0005_rename_no_of_lisners_song_no_of_listeners_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='downloads',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='radio_airplay',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='social_media_mentions',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='streams',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='musicapp.artist'),
        ),
    ]
