# Generated by Django 5.1.4 on 2025-01-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0005_album_cover_image_url_artist_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_cover_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
