# Generated by Django 5.1.4 on 2024-12-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_song_downloads_song_radio_airplay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='albums/'),
        ),
    ]
