# Generated by Django 5.1.4 on 2025-01-28 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_alter_album_cover_image_url_alter_artist_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='image',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_cover',
        ),
    ]
