# Generated by Django 5.1.4 on 2024-12-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0007_alter_album_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artists/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_cover',
            field=models.ImageField(blank=True, null=True, upload_to='song_cover/'),
        ),
    ]
