# Generated by Django 5.1.4 on 2025-02-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0007_remove_album_cover_image_remove_artist_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_duration',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
