# Generated by Django 5.1.4 on 2024-12-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0008_alter_artist_image_alter_song_song_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_cover',
            field=models.ImageField(blank=True, null=True, upload_to='song_covers/'),
        ),
    ]
