# Generated by Django 5.1.4 on 2025-01-02 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0011_album_id_artist_id_song_id_alter_album_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='album',
            new_name='album_id',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artist',
            new_name='artist_id',
        ),
    ]
