# Generated by Django 5.1.4 on 2025-01-02 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0012_rename_album_song_album_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='album_id',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artist_id',
            new_name='artist',
        ),
    ]
