# Generated by Django 5.1.4 on 2025-01-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0015_song_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('Pop', 'Pop'), ('Rock', 'Rock'), ('Hip-Hop', 'Hip-Hop'), ('Jazz', 'Jazz'), ('Electronic', 'Electronic'), ('Mixed', 'Mixed'), ('Other', 'Other')], max_length=50),
        ),
    ]
