# Generated by Django 5.1.4 on 2025-01-06 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0016_alter_song_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='popularity',
        ),
    ]
