# Generated by Django 5.1.4 on 2025-01-06 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0017_remove_song_popularity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['name'], 'verbose_name_plural': 'Songs'},
        ),
        migrations.RenameField(
            model_name='song',
            old_name='title',
            new_name='name',
        ),
    ]
