# Generated by Django 5.1.4 on 2025-01-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0018_alter_song_options_rename_title_song_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-title'], 'verbose_name_plural': 'Albums'},
        ),
    ]
